image: Visual Studio 2017
version: 1.9.{build}

platform: Any CPU
configuration: Release

skip_tags: true

before_build:
  - ps: dotnet restore

build:
  parallel: true
  project: EfCore.InMemoryHelpers.sln

for:
  - branches:
      only:
        - master

    dotnet_csproj:
      patch: true
      file: 'Directory.Build.props'
      version: '{version}'

    skip_commits:
      files:
        - 'test/**/*'
        - '**/*.md'
        - '**/*.txt'
        - '.gitignore'
        - 'appveyor.yml'

    artifacts:
      - path: nugets\**\*.nupkg

    deploy:
      - provider: Environment
        name: NuGet

      - provider: Environment
        name: GitHub

