image: Visual Studio 2017
version: 1.8.{build}

platform: Any CPU
configuration: Release

dotnet_csproj:
  patch: true
  file: 'Directory.Build.props'
  version: '{version}'

before_build:
  - ps: dotnet restore

build:
  parallel: true
  project: EfCore.InMemoryHelpers.sln

deploy:
  provider: NuGet
  api_key:
    secure: MITJCVEmcj6Gut+nSQIcEXnYhh75shmj5yxWhRDgbSSdEhqhuqiQpLdsSj9w2Sd/
  skip_symbols: false
  artifacts: nugets\**\*.nupkg
  on:
    branch: master

artifacts:
  - path: nugets\**\*.nupkg
