image: Visual Studio 2017
version: 1.9.{build}

platform: Any CPU
configuration: Release

skip_commits:
  files:
    - test/*
    - '**/*.md'
    - '**/*.txt'
    - '.gitignore'
    - 'appveyor.yml'

dotnet_csproj:
  patch: true
  file: 'Directory.Build.props'
  version: '{version}'

before_build:
  - ps: dotnet restore

build:
  parallel: true
  project: EfCore.InMemoryHelpers.sln

deploy:
  provider: Environment
  name: NuGet
  on:
    branch: master

deploy:
  provider: Environment
  name: GitHub
  on:
    branch: master

artifacts:
  - path: nugets\**\*.nupkg
