image: Visual Studio 2017
version: 1.9.{build}

platform: Any CPU
configuration: Release

skip_commits:
  files:
    - test/*
    - '**/*.md'
    - '**/*.txt'
    - '.gitignore'
    - 'appveyor.yml'

dotnet_csproj:
  patch: true
  file: 'Directory.Build.props'
  version: '{version}'

before_build:
  - ps: dotnet restore

build:
  parallel: true
  project: EfCore.InMemoryHelpers.sln

deploy:
  provider: NuGet
  api_key:
    secure: eePIAkQ9zcszMCrpgPkk5LcT0AW7SM/RXVTFem5CA7fuoJ30VQwJMXPxa1w4RiRK
  skip_symbols: false
  on:
    branch: master

artifacts:
  - path: nugets\**\*.nupkg
