version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: dotnet build src --configuration Release
test_script:
- cmd: >-
    %xunit20%\xunit.console src\Tests\bin\Release\net471\Tests.dll
artifacts:
- path: nugets\**\*.nupkg